'use client'

import { useState } from 'react'

// Lets Daniel generate the personal API key his own coaching-conversation
// in claude.ai uses to add DL Trainer as a custom MCP connector (see
// STATUS.md). Same "write-only secret, shown once at generation" pattern
// GitHub/Stripe personal-access tokens use — deliberately stricter than
// how the LLM API key on this page works (that one the user already has a
// copy of from their own provider's dashboard; this one is generated by
// us, so if it's never shown again there's no way to recover it without
// rotating). After the first reveal, only "a key exists, created on X" is
// shown — never the raw value again.
export default function McpConnectorCard({ hasKey, createdAt }: { hasKey: boolean; createdAt: string | null }) {
  const [generatedKey, setGeneratedKey] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState<'key' | 'url' | null>(null)

  const origin = typeof window !== 'undefined' ? window.location.origin : ''
  // Leads with the key-in-URL fallback route (app/api/mcp/[key]/route.ts):
  // Daniel's real claude.ai screen turned out to ask for OAuth "Client ID"/
  // "Client secret" fields with no visible custom-header option, which the
  // header-based URL below depends on — a URL with nothing left to
  // configure sidesteps that screen entirely. The header variant is kept as
  // a secondary option for whoever's account does show a headers field,
  // since Anthropic's own docs prefer that over a URL-embedded credential.
  const keyInUrlConnectorUrl = generatedKey ? `${origin}/api/mcp/${generatedKey}` : ''
  const headerConnectorUrl = `${origin}/api/mcp`

  async function generate() {
    setGenerating(true)
    setError('')
    try {
      const res = await fetch('/api/profile/mcp-key', { method: 'POST' })
      const data = await res.json()
      if (res.ok) setGeneratedKey(data.key)
      else setError(data.error ?? 'Något gick fel')
    } catch {
      setError('Nätverksfel')
    }
    setGenerating(false)
  }

  function copy(text: string, which: 'key' | 'url') {
    navigator.clipboard?.writeText(text)
    setCopied(which)
    setTimeout(() => setCopied(null), 2000)
  }

  return (
    <div className="bg-card border border-edge rounded-2xl p-4 flex flex-col gap-3">
      <div>
        <div className="text-xs text-muted uppercase tracking-wider">Coaching-koppling (MCP)</div>
        <p className="text-muted text-xs mt-0.5">Låt din egen coaching-chatt i claude.ai läsa dina siffror direkt, utan skärmdumpar.</p>
      </div>

      {generatedKey ? (
        <div className="flex flex-col gap-3">
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-3">
            <p className="text-amber-400 text-xs font-semibold mb-2">Spara nyckeln nu — den visas bara den här gången.</p>
            <div className="flex items-center gap-2">
              <code className="flex-1 bg-bg rounded-lg px-3 py-2 text-xs text-fg break-all">{generatedKey}</code>
              <button type="button" onClick={() => copy(generatedKey, 'key')} className="text-xs bg-bg border border-edge px-3 py-2 rounded-lg text-fg hover:border-accent transition-colors flex-shrink-0">
                {copied === 'key' ? 'Kopierad!' : 'Kopiera'}
              </button>
            </div>
          </div>
          <div className="text-xs text-muted flex flex-col gap-1.5">
            <p>I claude.ai → Inställningar → Connectors → Lägg till egen connector, klistra in den här adressen (nyckeln sitter redan i den, inget mer att fylla i):</p>
            <div className="flex items-center gap-2">
              <code className="flex-1 bg-bg rounded-lg px-3 py-2 text-fg break-all">{keyInUrlConnectorUrl}</code>
              <button type="button" onClick={() => copy(keyInUrlConnectorUrl, 'url')} className="text-xs bg-bg border border-edge px-3 py-2 rounded-lg text-fg hover:border-accent transition-colors flex-shrink-0">
                {copied === 'url' ? 'Kopierad!' : 'Kopiera'}
              </button>
            </div>
            <p>Ser du fält för &quot;Client ID&quot;/&quot;Client secret&quot; eller liknande inloggningsuppgifter — lämna dem tomma och gå vidare. De hör till connectors som kräver att man loggar in på en tredjepartstjänst, vilket den här inte gör.</p>
            <details className="mt-1">
              <summary className="cursor-pointer text-fg">Vill du hellre ha nyckeln i ett eget fält istället för i adressen?</summary>
              <div className="flex flex-col gap-1.5 mt-1.5">
                <div className="flex items-center gap-2">
                  <code className="flex-1 bg-bg rounded-lg px-3 py-2 text-fg break-all">{headerConnectorUrl}</code>
                  <button type="button" onClick={() => copy(headerConnectorUrl, 'key')} className="text-xs bg-bg border border-edge px-3 py-2 rounded-lg text-fg hover:border-accent transition-colors flex-shrink-0">
                    {copied === 'key' ? 'Kopierad!' : 'Kopiera'}
                  </button>
                </div>
                <p>Om skärmen har ett &quot;Request headers&quot;-fält: namn <code className="text-fg">authorization</code>, värde <code className="text-fg">Bearer {generatedKey}</code> (hela texten, inklusive ordet Bearer).</p>
              </div>
            </details>
          </div>
        </div>
      ) : (
        <>
          {hasKey && createdAt && (
            <p className="text-muted text-xs">Nyckel skapad {new Date(createdAt).toLocaleDateString('sv-SE')}. Ny nyckel gör den gamla ogiltig omedelbart.</p>
          )}
          <button
            type="button"
            onClick={generate}
            disabled={generating}
            className="text-xs bg-bg border border-edge px-3 py-2 rounded-lg text-fg hover:border-accent transition-colors self-start disabled:opacity-50"
          >
            {generating ? 'Genererar...' : hasKey ? 'Rotera nyckel' : 'Generera nyckel'}
          </button>
        </>
      )}
      {error && <p className="text-red-400 text-xs">{error}</p>}
    </div>
  )
}
